name: Update Data

on:
  schedule:
    # Run at 00:00 and 12:00 GMT+7 -> 17:00 and 05:00 UTC
    - cron: '0 17,5 * * *'

  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add github token to code file
        run: sed -i "s/GITHUB_TOKEN/${{ secrets.gh_token }}/g" run.ipynb

      - name: Push kernel to kaggle
        uses: Joel-hanson/kaggle-kernel-actions@V1
        with:
          kaggle_username: ${{ secrets.kaggle_username }}
          kaggle_key: ${{ secrets.kaggle_key }}
          kaggle_make_new_kernel: true
          kernel_id: phamson02/vnnews-script
          code_file_path: run.ipynb
          language: python
          kernel_type: notebook
          is_private: true
          enable_gpu: true
          enable_internet: true
